#!/usr/bin/env fish

set -l script (status filename)

set -l msg "
Usage:

  $script <package-name>

  OR

  $script <directory-name-relative-to-packages> <package-name>

Example:

  $script cudatext

  $script cudatext cudatext-gtk2-aarch64
"

switch (count $argv)
  case 1
    set -l name $argv[1]

    copr-cli buildscm \
      --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
      --commit 'master' \
      --subdir $name \
      --spec "$name.spec" \
      --enable-net 'on' \
      'zliced13/figma-linux'

  case 2
    set -l subdir $argv[1]
    set -l name $argv[2]

    copr-cli buildscm \
      --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
      --commit 'master' \
      --subdir $subdir \
      --spec "$name.spec" \
      --enable-net 'on' \
      'zliced13/figma-linux'

  case '*'
    set_color red
    printf "ERROR: Invalid Usage!\n"
    set_color normal

    echo $msg
    exit 1
end
