#!/usr/bin/env fish

set -l script_dir (status dirname)

set -l webhook_rebuild $argv[1]

# echo $webhook_rebuild

for v in (fd 'spec' "$script_dir/.." -t file --format '{}')
  # Get subdir name (ie. the directory that contains the spec file(s))
  set -l split_dir (string split '/' $v)
  set -l subdir $split_dir[-2]
  set -l name (basename -s '.spec' $split_dir[-1])

  echo '--------------------------------------------'
  echo 'Clone URL: https://github.com/kris3713/figma-linux-copr.git'
  echo 'Commitish: master'
  echo "Subdir: $name"
  echo "Spec: $name.spec"
  echo "Pkg Name: $name"
  echo "Webhook Rebuild: $webhook_rebuild"
  echo 'COPR Project: zliced13/figma-linux'

  copr-cli edit-package-scm \
    --clone-url 'https://github.com/kris3713/figma-linux-copr.git' \
    --commit 'master' \
    --subdir $subdir \
    --spec "$name.spec" \
    --name $name \
    --webhook-rebuild $webhook_rebuild \
    'zliced13/figma-linux'
end
