#!/usr/bin/env python

import re
import sys
from logging import error
from typing import Any

import requests
from jsonpath_ng import JSONPath, parse


def parse_json(url: str, regex_str: str, jsonpath_expr: str):
    """
    Parses JSON content from a URL and
    extracts the desired information using
    regular expressions and JSONPath expressions.
    """

    if jsonpath_expr.__contains__("?"):
        error("JSONPath expression contains a question mark!")
        error("Conditional JSONPath expressions are not supported!")
        exit(1)

    result = ''

    # Compile the regular expression from string
    regex = re.compile(regex_str) if regex_str != '' else None

    # Parse the JSONPath expression from string
    jsonPath: JSONPath = parse(jsonpath_expr)

    # Invoke a new HTTP GET request
    response = requests.get(url)
    json_content = response.json()

    keys: list[Any] = jsonPath.find(json_content)

    for key in keys:
        if regex is not None:
            matches = regex.search(str(key.value))

            if matches is not None:
                if matches.group(1) is None:
                    result = matches.group(0)
                else:
                    result = matches.group(1)
        else:
            result = str(key.value)

    print(result)
# end of parse_json

# Allow the user to pass in the arguments from the command line
parse_json(sys.argv[1], sys.argv[2], sys.argv[3])

# # This is how it should be used
# parse_json('https://dl.pstmn.io/changelog?channel=stable&platform=linux64', '', '$.changelog[0].name')

# # This is how it should be used in cli
# ./scripts/parse-json 'https://dl.pstmn.io/changelog?channel=stable&platform=linux64' '' '$.changelog[0].name'
