#!/usr/bin/env python

import re
import sys
from lxml import etree
import requests


def parse_xml(url: str, regex_str: str, xpath_expr: str):
    """
    Parses XML content from a URL and
    extracts the desired information using
    regular expressions and XPath expressions.
    """

    result = ''

    # Compile the regular expression from string
    regex = re.compile(regex_str) if regex_str != '' else None

    # Invoke a new HTTP GET request
    response = requests.get(url)
    xml_content = etree.fromstring(response.content)

    #  Find all the elements that were captured the XPath expression
    elements = xml_content.xpath(xpath_expr)

    for e in elements:
        # If you want the text content of the element:
        # print(element.text_content())
        # If you want the HTML representation of the element:
        v = etree.tostring(e).decode()

        if regex is not None:
            matches = regex.search(v)

            if matches is not None:
                if matches.group(1) is None:
                    result = matches.group(0)
                else:
                    result = matches.group(1)
        else:
            result = v

    print(result)
# end of parse_xml

# Allow the user to pass in the arguments from the command line
parse_xml(sys.argv[1], sys.argv[2], sys.argv[3])
