#!/usr/bin/env python

import sys
from lxml import html
import requests


def test_xpath(url: str, xpath_expr: str):
    """
    Used for testing XPath expressions on HTML/XML content from a URL.
    """

    # Invoke a new HTTP GET request
    response = requests.get(url)
    html_content = html.fromstring(response.content)

    #  Find all the elements that were captured the XPath expression
    elements = html_content.xpath(xpath_expr)

    for e in elements:
        # If you want the text content of the element:
        # print(element.text_content())
        # If you want the HTML representation of the element:
        v = html.tostring(e).decode()

        print(v)
# end of test_xpath
